
-- Categories table
CREATE TABLE category (
                          id bigint generated by default as identity primary key,
                          name VARCHAR(255),
                          description VARCHAR(255)
);

-- Users table
CREATE TABLE app_users (
                           username varchar(255) primary key,
                           password varchar(255),
                           name varchar(255),
                           surname varchar(255),
                           isAccountNonExpired boolean default true,
                           isAccountNonLocked boolean default true,
                           isCredentialsNonExpired boolean default true,
                           isEnabled boolean default true,
                           role varchar(50)
);

-- Boats table
CREATE TABLE boat (
                      id bigint generated by default as identity primary key,
                      name VARCHAR(255),
                      description VARCHAR(255),
                      location VARCHAR(255),
                      price DOUBLE PRECISION,
                      capacity INTEGER,
                      status varchar(50) NOT NULL DEFAULT 'AVAILABLE',
                      category_id INTEGER REFERENCES category(id)
);

-- Orders table
CREATE TABLE customer_orders (
                                 id bigint generated by default as identity primary key,
                                 user_username VARCHAR(255) REFERENCES app_users(username),
                                 status varchar(50) NOT NULL DEFAULT 'PENDING'
);

-- Join table for ManyToMany between orders and boats
CREATE TABLE customer_orders_boats (
                                       order_id INTEGER NOT NULL REFERENCES customer_orders(id),
                                       boats_id INTEGER NOT NULL REFERENCES boat(id),
                                       PRIMARY KEY (order_id, boats_id)
);

-- Optional: Insert example categories
INSERT INTO category (name, description) VALUES
                                             ('Sailboat', 'Sail powered boats'),
                                             ('Motorboat', 'Boats with motor engines'),
                                             ('Kayak', 'Small narrow watercraft');

